/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secante;

/**
 *
 * @author cobak
 */
public class dnjSecante extends javax.swing.JDialog {

    /**
     * Creates new form njSecante
     */
    public dnjSecante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        Error = new javax.swing.JTextField();
        Xs = new javax.swing.JTextField();
        Secante = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaSecante = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Xi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        Error.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErrorActionPerformed(evt);
            }
        });
        getContentPane().add(Error);
        Error.setBounds(228, 39, 51, 20);

        Xs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XsActionPerformed(evt);
            }
        });
        getContentPane().add(Xs);
        Xs.setBounds(170, 39, 46, 20);

        Secante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Secante.setText("Secante");
        Secante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecanteActionPerformed(evt);
            }
        });
        getContentPane().add(Secante);
        Secante.setBounds(21, 39, 77, 23);

        tablaSecante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaSecante);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(21, 80, 460, 200);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("Xi");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(181, 11, 24, 22);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setText("Xi-1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(118, 11, 34, 22);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("ERROR");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(228, 11, 60, 22);

        Xi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XiActionPerformed(evt);
            }
        });
        getContentPane().add(Xi);
        Xi.setBounds(108, 39, 52, 20);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/geometry-1023846__340.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-50, -60, 650, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ErrorActionPerformed

    private void SecanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecanteActionPerformed
        double xi = Double.parseDouble(this.Xi.getText().trim());
        double xs = Double.parseDouble(this.Xs.getText().trim());
        double error = Double.parseDouble(this.Error.getText().trim());
        
        ctrlSecante ctrl = new ctrlSecante(xi,xs,error);
        tablaSecante tabla = ctrl.getTablaSecante();
        this.tablaSecante.setModel(tabla);// TODO add your handling code here:
    }//GEN-LAST:event_SecanteActionPerformed

    private void XiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XiActionPerformed

    private void XsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XsActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Error;
    private javax.swing.JButton Secante;
    private javax.swing.JTextField Xi;
    private javax.swing.JTextField Xs;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaSecante;
    // End of variables declaration//GEN-END:variables
}
