/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Newton;

//import Newton.*;

/**
 *
 * @author cobak
 */
public class dnjNewton extends javax.swing.JDialog {

    /**
     * Creates new form njSecante
     */
    public dnjNewton(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        Error = new javax.swing.JTextField();
        Xi = new javax.swing.JTextField();
        Newton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaNewton = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        Error.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErrorActionPerformed(evt);
            }
        });
        getContentPane().add(Error);
        Error.setBounds(180, 40, 51, 20);

        Xi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XiActionPerformed(evt);
            }
        });
        getContentPane().add(Xi);
        Xi.setBounds(120, 40, 46, 20);

        Newton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Newton.setText("Newton");
        Newton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewtonActionPerformed(evt);
            }
        });
        getContentPane().add(Newton);
        Newton.setBounds(21, 39, 77, 23);

        tablaNewton.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaNewton);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(21, 80, 460, 200);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("Xi");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 20, 24, 22);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("ERROR");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 20, 60, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ErrorActionPerformed

    private void NewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewtonActionPerformed
        double xi = Double.parseDouble(this.Xi.getText().trim());
        double error = Double.parseDouble(this.Error.getText().trim());
        
        ctrlNewton ctr = new ctrlNewton(xi,error);
        tablaNewton tabla = ctr.getTablaNewton();
        this.tablaNewton.setModel(tabla);// TODO add your handling code here:
    }//GEN-LAST:event_NewtonActionPerformed

    private void XiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XiActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Error;
    private javax.swing.JButton Newton;
    private javax.swing.JTextField Xi;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaNewton;
    // End of variables declaration//GEN-END:variables
}
