/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg4atema2coba;

import Aproximaciones.dlgAproximaciones;
import Biseccion.dnjBiseccion;
import Secante.dnjSecante;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author cobak
 */
public class FmrPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FmrPrincipal
     */
    public FmrPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(628,420);
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EtiquetaSeis = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.gray);
        getContentPane().setLayout(null);

        EtiquetaSeis.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        EtiquetaSeis.setText("Salir");
        EtiquetaSeis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, null));
        EtiquetaSeis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EtiquetaSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EtiquetaSeisActionPerformed(evt);
            }
        });
        getContentPane().add(EtiquetaSeis);
        EtiquetaSeis.setBounds(70, 290, 130, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bola-de-metal-520062da873c7.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 460);

        jMenu1.setText("Metodos Ecuaciones No Lineales");
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Aproximaciones");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("Biseccion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Secante");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       dnjBiseccion dlg = new dnjBiseccion(this, true);
       dlg.setSize(525,330);
       dlg.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        dnjSecante dlg = new dnjSecante(this,true);
        dlg.setSize(525,330);
        dlg.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void EtiquetaSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EtiquetaSeisActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_EtiquetaSeisActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        dlgAproximaciones dlg = new dlgAproximaciones(this,true);
        dlg.setMaximumSize(null);
        dlg.setVisible(true);
        dlg.setLocationRelativeTo(dlg);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton EtiquetaSeis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
