/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg4atema2coba;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author cobak
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EtiquetaUno = new javax.swing.JLabel();
        EtiquetaDos = new javax.swing.JLabel();
        EtiquetaTres = new javax.swing.JLabel();
        EtiquetaCuatro = new javax.swing.JLabel();
        EtiquetaCinco = new javax.swing.JLabel();
        EtiquetaSeis = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        getContentPane().setLayout(null);

        EtiquetaUno.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 30)); // NOI18N
        EtiquetaUno.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaUno.setText("Intituto Tecnologico");
        getContentPane().add(EtiquetaUno);
        EtiquetaUno.setBounds(200, 30, 330, 40);

        EtiquetaDos.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 30)); // NOI18N
        EtiquetaDos.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaDos.setText("Superior de Valladolid");
        getContentPane().add(EtiquetaDos);
        EtiquetaDos.setBounds(260, 80, 340, 40);

        EtiquetaTres.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        EtiquetaTres.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaTres.setText("Tema: Métodos de solucion no lineal");
        getContentPane().add(EtiquetaTres);
        EtiquetaTres.setBounds(270, 130, 270, 50);

        EtiquetaCuatro.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 30)); // NOI18N
        EtiquetaCuatro.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaCuatro.setText("Profesor");
        getContentPane().add(EtiquetaCuatro);
        EtiquetaCuatro.setBounds(230, 190, 200, 40);

        EtiquetaCinco.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 30)); // NOI18N
        EtiquetaCinco.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaCinco.setText("MM. Jorge Pool Cen");
        getContentPane().add(EtiquetaCinco);
        EtiquetaCinco.setBounds(260, 240, 350, 30);

        EtiquetaSeis.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        EtiquetaSeis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono.png"))); // NOI18N
        EtiquetaSeis.setText("CONTINUAR");
        EtiquetaSeis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, null));
        EtiquetaSeis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EtiquetaSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EtiquetaSeisActionPerformed(evt);
            }
        });
        getContentPane().add(EtiquetaSeis);
        EtiquetaSeis.setBounds(50, 290, 230, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cubos-azules1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EtiquetaSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EtiquetaSeisActionPerformed
        // TODO add your handling code here:
       FmrPrincipal frm = new FmrPrincipal();
       frm.setTitle("Metodos de Solución de Ecuaciones");
       frm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       frm.setSize(628,420);
       frm.setLocationRelativeTo(null); //centrar
       frm.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_EtiquetaSeisActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EtiquetaCinco;
    private javax.swing.JLabel EtiquetaCuatro;
    private javax.swing.JLabel EtiquetaDos;
    private javax.swing.JToggleButton EtiquetaSeis;
    private javax.swing.JLabel EtiquetaTres;
    private javax.swing.JLabel EtiquetaUno;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
