/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aproximaciones;

/**
 *
 * @author Familiadc
 */
public class dlgAproximaciones extends javax.swing.JDialog {

    /**
     * Creates new form dlgAproximaciones
     */
    public dlgAproximaciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tAproximaciones = new javax.swing.JTable();
        jBAproximacion = new javax.swing.JButton();
        jInicial = new javax.swing.JLabel();
        jError = new javax.swing.JLabel();
        JTextValorI = new javax.swing.JTextField();
        jTextError = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        tAproximaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tAproximaciones);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 80, 460, 250);

        jBAproximacion.setText("Aproximacion");
        jBAproximacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAproximacionActionPerformed(evt);
            }
        });
        getContentPane().add(jBAproximacion);
        jBAproximacion.setBounds(20, 50, 97, 23);

        jInicial.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jInicial.setText("Valor Inicial");
        getContentPane().add(jInicial);
        jInicial.setBounds(124, 20, 80, 33);

        jError.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jError.setText("Error");
        getContentPane().add(jError);
        jError.setBounds(210, 20, 62, 33);

        JTextValorI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextValorIActionPerformed(evt);
            }
        });
        getContentPane().add(JTextValorI);
        JTextValorI.setBounds(123, 51, 80, 20);
        getContentPane().add(jTextError);
        jTextError.setBounds(213, 51, 60, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/73182469ec71fb31fa3677c65e0be44f.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-40, -20, 590, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jBAproximacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAproximacionActionPerformed
        // TODO add your handling code here
        double vInicial, error;
        error = Double.parseDouble(this.jTextError.getText().trim());
        vInicial = Double.parseDouble(this.JTextValorI.getText().trim());
        
        metodoAproximaciones mtApro = new metodoAproximaciones(vInicial,error);
        tablaAproximaciones tabala = mtApro.getTablaAproximacciones();
        this.tAproximaciones.setModel(tabala);
       
        
    }//GEN-LAST:event_jBAproximacionActionPerformed

    private void JTextValorIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextValorIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextValorIActionPerformed
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextValorI;
    private javax.swing.JButton jBAproximacion;
    private javax.swing.JLabel jError;
    private javax.swing.JLabel jInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextError;
    private javax.swing.JTable tAproximaciones;
    // End of variables declaration//GEN-END:variables
}
